---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k0rdent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/k0rdent/kcm/charts
    targetRevision: "0.1.0"
    chart: kcm
  destination:
    name: "in-cluster"
    namespace: kcm-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
