---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue
resources:
  - namespace.yaml
  - ../../../../cluster-deployments/aws
  - credential.yaml
patches:
  - target:
      kind: ClusterDeployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: "cluster-1"
